name: Flask CI/CD Pipeline

on:
  push:
    branches:
      - medium

jobs:
  checkout-code:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

  security-check:
    runs-on: self-hosted
    needs: checkout-code

    steps:
      - name: Trivy FS Scan
        run: |
            trivy fs --format table -o fs-report.json .
      - name: Gitleaks Code Scan
        run: | 
            gitleaks detect --no-git  --source . --config .gitleaks.toml -r gitleaks-report.json -f json --verbose 